#!/usr/bin/env python3
"""Generate campaign vectors restricted to frames that are actually injectable.

Measured injectable columns (campaign/2026-09-01_validation/injmap_fullcols.log,
244 grid points, deterministic per column, uniform across minors):

    18-27, 34-55   real device columns, injectable in both halves
    0-17, 28-33    never injectable
    56             CONFIRMED FALSE POSITIVE - fires with nothing planted
                   (the out-of-device artifact region; 0x001C02 is already in
                   masked_frames_c)
    57-60          beyond cols_per_row_c = 56; excluded

    half=1, cols 43-55 showed a minor-dependent soft spot (1 of 4 sweeps), so
    those are excluded from the top half by default.

Vectors are single-bit only, so that this file measures the ECC-located path
alone. Multi-bit-in-frame vectors ARE visible to the capture flag (ECCERROR
without ECCERRORSINGLE) and are exercised by campaign_conc.tcl instead.
"""
import random

random.seed(20260903)

# 2026-09-03 (ILA, FINDINGS 18.6): columns 19-24 hold the AXI interconnect's
# SRL read-data FIFOs (bottom rows Y38-52 and their top-half mirrors). A frame
# read-modify-write there restores a stale FIFO snapshot into a live AXI
# converter and hangs the PS bus - every DAP wedge of this project. Excluded.
COLS_BOTH = [18, 25, 26, 27] + list(range(34, 43))
COLS_BOT_ONLY = list(range(43, 56))          # half 0 only
# Per-column minor counts from rtl/v1.8/device_geometry_pkg.vhd (measured).
# Columns 34 and 54 have 30 minors, 22/25/42/46/49 have 28: the two vectors the
# honest campaign could not detect on either scan sat at minors 30 and 28 in
# cols 34 and 54. A flat cap does not work; use the table, minus a margin of 2.
import re, pathlib
_pkg = pathlib.Path(__file__).resolve().parents[1] / "rtl/v1.8/device_geometry_pkg.vhd"
def _minors(name):
    body = re.search(name + r"\s*:\s*col_minors_arr_t\s*:=\s*\((.*?)\);", _pkg.read_text(), re.S).group(1)
    return {int(a): int(b) for a, b in re.findall(r"(\d+)\s*=>\s*(\d+)", body)}
TOP_MINORS = _minors("top_col_minors_c")   # FAR bit22 = 0
BOT_MINORS = _minors("bot_col_minors_c")   # FAR bit22 = 1
MARGIN = 2
N = 150

out = []
while len(out) < N:
    half = random.randint(0, 1)
    cols = COLS_BOTH + (COLS_BOT_ONLY if half == 0 else [])
    col = random.choice(cols)
    nmin = (TOP_MINORS if half == 0 else BOT_MINORS).get(col, 0) - MARGIN
    if nmin <= 0:
        continue
    minor = random.randrange(nmin)
    far = (half << 22) | (col << 7) | minor
    word = random.randint(0, 100)
    bit = random.randint(0, 31)
    v = (far, word, 1 << bit)
    if v not in out:
        out.append(v)

with open("campaign_vectors_reachable.tcl", "w") as f:
    f.write("# Campaign vectors restricted to measured-injectable frames.\n")
    f.write("# Generated by gen_vectors.py; see FINDINGS.md section 12.\n")
    f.write("# {FAR word mask kind}\n")
    f.write("set VEC {\n")
    for far, word, mask in out:
        f.write(f"  {{0x{far:06X} {word} 0x{mask:08X} single}}\n")
    f.write("}\n")

cols = sorted({(f >> 7) & 0x3FF for f, _, _ in out})
print(f"wrote campaign_vectors_reachable.tcl: {len(out)} vectors")
print(f"columns used: {cols}")
print(f"halves: {sorted({(f>>22)&1 for f,_,_ in out})}")
